### ISSUE TITLE
Under the 'typography' setting, letter-spacing, font-weight, font-size aren't working 

### ISSUE THREAD

**Issue by azizulDev** [pickplugins/post-grid#48]

**Comment by pickplugins** [comment]
Fixed

**Comment by azizulDev** [comment]
Hi, I checked your latest updates and found out the issue is still there!
The 'typography' settings under **post excerpt** are working on the **Editor** but not on the **front end**!
And the other 'typography' settings under **read more** aren't working on the **Editor**.

**Comment by pickplugins** [comment]
Fixed Fixed
